# -*- mode: ruby -*-
# vi: set ft=ruby :

ram = 2048
cpu = 2
private_ip = "10.0.0.10"

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos7"
  config.vm.provider "virtualbox" do |v|
    v.memory = ram
    v.cpus = cpu
  end
  config.vm.network "private_network", ip: private_ip
end
