# -*- mode: ruby -*-
# vi: set ft=ruby :

Ram = 2048
cpu = 2

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos7"
  config.vm.provider "virtualbox" do |v|
    v.memory = Ram
    v.cpus = cpu
  end  
end
