# -*- mode: ruby -*-
# vi: set ft=ruby :

ram = 1024
cpu = 1
private_ip = "10.0.0.10"

Vagrant.configure("2") do |config|
  config.vm.box = "kamgaingrodrigue3/nginx"
  config.vm.box_version = "1.0"
  config.vm.hostname = "nginx"
  config.vm.provider "virtualbox" do |v|
    v.memory = ram
    v.cpus = cpu
  end
  config.vm.network "private_network", ip: private_ip
  config.vm.synced_folder "static-website-example/", "/usr/share/nginx/html/"
end
